Registration API Integration
Seven-Musketeers/frontend pull request #36
Opened 2023-11-19 07:58 UTC by Anupamaraie

Registration API Integrated.

Desc:
It shows an error when entries other than lspp in type is made.
It says full name but it only takes one string.

Here is the successful registration otherwise.
<img width="610" alt="image" src="https://github.com/Leapblog/frontend/assets/91787285/a3705d04-34b3-482a-8951-b5ab62f0a8c2">
<img width="485" alt="image" src="https://github.com/Leapblog/frontend/assets/91787285/b8e371e2-4512-4eab-83bc-1fa89873f908">

2023-11-19 11:23 UTC, purnasth requested changes
Also, whenever a registered user tries to login to the website with the username and password, the user should be able to login and be redirected to the main page, where they can comment on and like the blog post. 

It is also necessary to employ password hashing to keep the user password secure when saving the password in the database. Is password hashing performed?

Please also remove the console.log() There is no purpose to display the message to the console.

2023-11-19 14:00 UTC, Anupamaraie commented
I have no idea about that. This backend wasn't done by me. So, can't really comment on others work.

2023-11-20 04:09 UTC, purnasth approved these changes

2023-11-20 04:09 UTC, merged

2023-11-21 15:45 UTC, thenishantsapkota commented
> Also, whenever a registered user tries to login to the website with the username and password, the user should be able to login and be redirected to the main page, where they can comment on and like the blog post.
> 
> It is also necessary to employ password hashing to keep the user password secure when saving the password in the database. Is password hashing performed?
> 
> Please also remove the console.log() There is no purpose to display the message to the console.

The password hashing and all the security measures are already implemented in the backend. It is foolproof.